FROM debian:bullseye
WORKDIR /opt
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip python3-pil iproute2 && \
    pip3 install flask && \
    rm -rf /var/lib/apt/lists/*
COPY camera.py /opt/camera.py
COPY startup.sh /opt/startup.sh
RUN chmod +x /opt/startup.sh
EXPOSE 8081
